FROM bcit.io/almalinux:9-latest as build

# from https://duo.com/docs/authproxy-reference#installation
RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 install <% image.vars['yum_build_deps'].each do |pkg| -%> \
    <%= pkg -%>
<% end -%>


# modified from https://github.com/jumanjihouse/docker-duoauthproxy/
WORKDIR /src
ADD https://dl.duosecurity.com/duoauthproxy-<%= image.vars['duoauthproxy_ver'] -%>-src.tgz /src/
RUN tar xzf duoauthproxy-*-src.tgz \
 && cd duoauthproxy-*-src \
 && make \ 
 && useradd duo \
 && cd duoauthproxy-build \
 && ./install --install-dir=/opt/duoauthproxy --service-user=duo --log-group=duo --create-init-script=no

FROM bcit.io/almalinux:9-latest

<%= snippet('labels', binding) -%>

RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 install <% image.vars['yum_runtime_deps'].each do |pkg| -%> \
    <%= pkg -%>
<% end -%>

COPY --from=build /opt/duoauthproxy/ /opt/duoauthproxy/
RUN useradd -s /sbin/nologin duo \
 && mkdir -p /opt/duoauthproxy/log \
 && chown -R duo:duo /opt/duoauthproxy/log

USER duo
CMD ["/opt/duoauthproxy/bin/authproxy"]
